### ISSUE TITLE
No Longer on US App Store?

### ISSUE THREAD

**Issue by delianides** [manosim/gitify-mobile#28]
I was trying to show a collegue your app but it's no longer on the US store. Will it be back?

**Comment by manosim** [comment]
Hello @delianides! The app was removed from the app store because my apple developer account expired and it is a bit pricy since I only had free apps on the app store(most of them are even open-source). I'll have a look around if anyone wants to "sponsor" the app by paying for the account (or if I make any more apps I'll obviously renew my account myself)!

For now feel free to download the source & install it with xcode etc - Sorry for the hassle!

**Comment by bobylito** [comment]
Hey I love your app, how can we help? Is there a tipping system that we could use to sponsor the distribution of the app?

**Comment by FezVrasta** [comment]
Can I build and install it even without a developer license?

**Comment by manosim** [comment]
Hello everyone! The app is now available again - you can find more information on https://github.com/manosim/gitify/issues/261!
